// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: compliance/compliance.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "compliance";

/** compliance/compliance.proto */

export enum ComplianceCheckStatus {
  COMPLIANCE_CHECK_STATUS_UNSPECIFIED = 0,
  COMPLIANCE_CHECK_STATUS_READY = 1,
  COMPLIANCE_CHECK_STATUS_IN_PROGRESS = 2,
  UNRECOGNIZED = -1,
}

export enum ComplianceAssessmentSource {
  COMPLIANCE_ASSESSMENT_SOURCE_UNSPECIFIED = 0,
  COMPLIANCE_ASSESSMENT_SOURCE_PROVIDER = 1,
  COMPLIANCE_ASSESSMENT_SOURCE_BLACKLIST = 2,
  COMPLIANCE_ASSESSMENT_SOURCE_WHITELIST = 3,
  UNRECOGNIZED = -1,
}

export enum ComplianceRetrievalSource {
  COMPLIANCE_RETRIEVAL_SOURCE_UNSPECIFIED = 0,
  COMPLIANCE_RETRIEVAL_SOURCE_PROVIDER = 1,
  COMPLIANCE_RETRIEVAL_SOURCE_CACHE = 2,
  COMPLIANCE_RETRIEVAL_SOURCE_POLICY = 3,
  UNRECOGNIZED = -1,
}

export interface CheckAddressComplianceRequest {
  address: string;
  network: string;
}

export interface ComplianceSignal {
  category: string;
  score: number;
}

export interface CheckAddressComplianceResponse {
  address: string;
  network: string;
  status: ComplianceCheckStatus;
  riskScore?: number | undefined;
  signals: ComplianceSignal[];
  checkedAt?: string | undefined;
  assessmentSource: ComplianceAssessmentSource;
  isHighRisk: boolean;
  retrievalSource: ComplianceRetrievalSource;
}

export const COMPLIANCE_PACKAGE_NAME = "compliance";

export interface ComplianceServiceClient {
  checkAddressCompliance(request: CheckAddressComplianceRequest): Observable<CheckAddressComplianceResponse>;
}

export interface ComplianceServiceController {
  checkAddressCompliance(
    request: CheckAddressComplianceRequest,
  ):
    | Promise<CheckAddressComplianceResponse>
    | Observable<CheckAddressComplianceResponse>
    | CheckAddressComplianceResponse;
}

export function ComplianceServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkAddressCompliance"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ComplianceService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ComplianceService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMPLIANCE_SERVICE_NAME = "ComplianceService";
